# PostgreSQL Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/s21_tic_tac_toe}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html